# -----------------------------------------------------------------
# C o n f i g   S e r v e r
# -----------------------------------------------------------------

### Konfigurationsdaten fuer das Profil "dev"
https://{{config-host}}/kunde/dev
Authorization: {{basic-auth-admin}}

### REST-Schnittstelle vom Config-Server
https://{{config-host}}/actuator
Authorization: {{basic-auth-admin}}

### Config-Server herunterfahren
POST https://{{config-host}}/actuator/shutdown
Authorization: {{basic-auth-admin}}

### Beans vom Config-Server
#https://{{config-host}}/actuator/beans
#Authorization: {{basic-auth-admin}}

# -----------------------------------------------------------------
# F l u e g e  M i c r o s e r v i c e
# -----------------------------------------------------------------

### Suche alle Flüge
https://{{host}}
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2
# ALPN: h2, http%2F1.1

### Suche alle Fluege mit falschem Passwort: 401 (Unauthorized)
https://{{host}}
Authorization: {{basic-auth-admin-falsch}}
ALPN: h2

### Suche alle Fluege mit fehlenden Rechten: 403 (Forbidden) -> UseCase nicht vorhanden
### https://{{host}}
### Authorization: {{basic-auth-alpha1}}
### ALPN: h2

### Suche mit vorhandener Flug-ID als admin
https://{{host}}/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit ungueltiger Flug-ID
https://{{host}}/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit nicht-vorhandener Flug-ID
https://{{host}}/99999999-9999-9999-9999-999999999999
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit falschem Passwort: 401 (Unauthorized)
https://{{host}}/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
Authorization: Basic {{basic-auth-admin-falsch}}
ALPN: h2

### Suche mit vorhandener Flug-ID als mitarbeiter
https://{{host}}/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
Authorization: {{basic-auth-alpha1}}
ALPN: h2

### Suche mit fehlender Berechtigung: 403 (Forbidden) -> Auch hier nicht passend für mein UseCase
### https://{{host}}/00000000-0000-0000-0000-000000000002
### Accept: application/hal+json
### Authorization: {{basic-auth-alpha1}}
### ALPN: h2

### Suche mit vorhandener Flug-ID und ETag
https://{{host}}/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
If-None-Match: "0"
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit vorhandener Flug-ID und falschem ETag
https://{{host}}/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
If-None-Match: 0
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit vorhandener Flugnummer
https://{{host}}/?flugnummer=NL0D2
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit vorhandenem AblugFlughafen
https://{{host}}/?abflugFlughafenIata=ATL
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit nicht-vorhandener Flugnummer
https://{{host}}/?flugnummer=XY999
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit vorhandener Airline und Ort
https://{{host}}/?airline=Lufthansa&abflugFlughafenIata=DXB
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2

### Suche mit vorhandenem Airline, Abflugflughafen und Gate
https://{{host}}/?airline=Easy+Jet&abflugFlughafenIata=ATL&gate=4
Accept: application/hal+json
Authorization: {{basic-auth-admin}}
ALPN: h2, ^^^q1

### Streaming mit allen Kunden
https://{{host}}
Accept: text/event-stream
Authorization: {{basic-auth-admin}}
ALPN: h2

### Einen neuen Kunden anlegen
POST https://{{host}}
Content-Type: application/json
ALPN: h2

< flug-neu.json

### Einen neuen Kunden mit ungueltigen Daten versuchen anzulegen
POST https://{{host}}
Content-Type: application/json
ALPN: h2

< flug-neu-invalid.json

### Einen Kunden mittels PUT aktualisieren
#PUT https://{{host}}/00000000-0000-0000-0000-000000000001
#If-Match: "0"
#Content-Type: application/json
#Authorization: {{basic-auth-admin}}
#ALPN: h2
#
#< flug-1-put.json

### Einen Kunden mittels PUT und ungueltigen Daten aktualisieren
PUT https://{{host}}/00000000-0000-0000-0000-000000000001
If-Match: "0"
Content-Type: application/json
Authorization: {{basic-auth-admin}}
ALPN: h2

< flug-1-put-invalid.json

### Einen Kunden mittels PUT und falschem Passwort aktualisieren: 401 (Unauthorized)
PUT https://{{host}}/00000000-0000-0000-0000-000000000001
If-Match: "0"
Content-Type: application/json
Authorization: {{basic-auth-admin-falsch}}
ALPN: h2

< flug-1-put.json




#### Einen Kunden mittels PATCH aktualisieren
#PATCH https://{{host}}/00000000-0000-0000-0000-000000000003
#If-Match: "0"
#Content-Type: application/json
#Authorization: {{basic-auth-admin}}
#ALPN: h2
#
#[
#  { "op": "replace", "path": "/nachname", "value": "Neuernameput" },
#  { "op": "replace", "path": "/email", "value": "new.email@test.deput" },
#  { "op": "add", "path": "/interessen", "value": "S" },
#  { "op": "remove", "path": "/interessen", "value": "L" }
#]
#
#### Einen Kunden mittels PATCH und ungueltigen Daten aktualisieren
#PATCH https://{{host}}/00000000-0000-0000-0000-000000000003
#If-Match: "0"
#Content-Type: application/json
#Authorization: {{basic-auth-admin}}
#ALPN: h2
#
#[
#  { "op": "replace", "path": "/email", "value": "emailungueltig@" }
#]
#
#### Einen Kunden mittels PATCH und falschem Passwort aktualisieren: 401 (Unauthorized)
#PATCH https://{{host}}/00000000-0000-0000-0000-000000000001
#If-Match: "0"
#Content-Type: application/json
#Authorization: {{basic-auth-admin-falsch}}
#ALPN: h2
#
#[
#  { "op": "replace", "path": "/nachname", "value": "Neuername" },
#  { "op": "replace", "path": "/email", "value": "new.email@test.de" },
#  { "op": "add", "path": "/interessen", "value": "R" },
#  { "op": "remove", "path": "/interessen", "value": "L" }
#]
#
#### Einen Kunden mittels PATCH und fehlenden Rechten aktualisieren: 403 (Forbidden)
#PATCH https://{{host}}/00000000-0000-0000-0000-000000000001
#If-Match: "0"
#Content-Type: application/json
#Authorization: {{basic-auth-alpha1}}
#ALPN: h2
#
#[
#  { "op": "replace", "path": "/nachname", "value": "Neuername" },
#  { "op": "replace", "path": "/email", "value": "new.email@test.de" },
#  { "op": "add", "path": "/interessen", "value": "R" },
#  { "op": "remove", "path": "/interessen", "value": "L" }
#]

### Löschen mit vorhandener Flug-ID
DELETE https://{{host}}/00000000-0000-0000-0000-000000000000
Authorization: {{basic-auth-admin}}
ALPN: h2

### Löschen mit nicht-vorhandener Flug-ID
DELETE https://{{host}}/FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF
Authorization: {{basic-auth-admin}}
ALPN: h2

### Löschen mit vorhandener Flug-ID und falschem Passwort: 401 (Unauthorized)
DELETE https://{{host}}/00000000-0000-0000-0000-000000000004
Authorization: {{basic-auth-admin-falsch}}
ALPN: h2

### Löschen mit vorhandener Flug-ID und fehlenden Rechten: 403 (Forbidden)
DELETE https://{{host}}/00000000-0000-0000-0000-000000000002
Authorization: {{basic-auth-alpha1}}
ALPN: h2


# -----------------------------------------------------------------
# P r a e f i x e   u n d   V e r s i o n e n (SWE)
# -----------------------------------------------------------------

### Suche Nachnamen mit Praefix
#https://{{host}}/nachname/a
#Authorization: {{basic-auth-admin}}
#ALPN: h2
#
#### Suche Emailadressen mit Praefix
#https://{{host}}/email/al
#Authorization: {{basic-auth-admin}}
#ALPN: h2

### Suche Version zu Kunde-ID
https://{{host}}/version/00000000-0000-0000-0000-000000000001
Authorization: {{basic-auth-admin}}
ALPN: h2

### Alle Rollen ermitteln
https://{{host}}/auth/rollen
Authorization: {{basic-auth-admin}}
ALPN: h2

# -----------------------------------------------------------------
# A c t u a t o r
# -----------------------------------------------------------------

### Uebersicht
https://{{actuator}}
Authorization: {{basic-auth-admin}}

### Status (erfordert Client fuer MongoDB)
https://{{actuator}}/info
Authorization: {{basic-auth-admin}}

### Health
https://{{actuator}}/health
Authorization: {{basic-auth-admin}}

### Features
https://{{actuator}}/features
Authorization: {{basic-auth-admin}}

### Spring Beans
https://{{actuator}}/beans
Authorization: {{basic-auth-admin}}

### Configuration Properties
https://{{actuator}}/configprops
Authorization: {{basic-auth-admin}}

### Umgebung und Properties
https://{{actuator}}/env
Authorization: {{basic-auth-admin}}

### Property server.port
https://{{actuator}}/env/server.port
Authorization: {{basic-auth-admin}}

### Property server.ssl.protocol
https://{{actuator}}/env/server.ssl.protocol
Authorization: {{basic-auth-admin}}

### Shutdown
POST https://{{actuator}}/shutdown
Authorization: {{basic-auth-admin}}
Content-Type: application/json

### Restart (nur Shutdown :-(
POST https://{{actuator}}/restart
Authorization: {{basic-auth-admin}}

### Beispiel 3: Abfrage ueber den Status der Instanz beim Registry-Server (401 :-(
http://{{host}}/service-registry/instance-status
Authorization: {{basic-auth-admin}}

# -----------------------------------------------------------------
# R e g i s t r y   S e r v e r   (Beispiel 3)
# -----------------------------------------------------------------

### Registrierte Services
https://{{consul-host}}/v1/agent/services

### Service "kunde"
https://{{consul-host}}/v1/agent/service/kunde-8444

### "Service Health" fuer Service mit Name "kunde"
https://{{consul-host}}/v1/agent/health/service/name/kunde

### "Service Health" fuer Service mit ID "kunde-8444"
https://{{consul-host}}/v1/agent/health/service/id/kunde-8444

### Service "bestellung"
https://{{consul-host}}/v1/agent/service/bestellung-8445

### Registrierte Checks
https://{{consul-host}}/v1/agent/checks

### Service "config"
http://{{consul-host}}/v1/agent/service/config-8888

### "Service Health" fuer Service mit Name "config"
http://{{consul-host}}/v1/agent/health/service/name/config

### "Service Health" fuer Service mit ID "config-8888"
http://{{consul-host}}/v1/agent/health/service/id/config-8888

# -----------------------------------------------------------------
# O P T I O N S, H E A D
# -----------------------------------------------------------------

#OPTIONS https://{{host}}
#Authorization: {{basic-auth-admin}}
#ALPN: h2

###

#HEAD https://{{host}}
#Authorization: {{basic-auth-admin}}
#ALPN: h2
